name: "dbt_aql"
version: "0.1.0"

config-version: 2

require-dbt-version: [">=1.2.0", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"