[tool.poetry]
name = "dbt-aql"
version = "0.1.5"
description = "A dbt package to query Activity Streams using a SQL-esque interface."
authors = ["Bryce Codell <bryce.codell@24analytics.co"]
license = "GNU"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
dbt-core = "1.3.3"
duckdb = "0.6.1"
dbt-duckdb = "^1.3.0"
dbt-postgres = "~1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
