version: 2

models:

  - name: dataset__filtered
    description: A test to validate the functionality of filter clauses in aql.
    data_tests:
      - dbt_utils.equality:
          compare_model: ref("output__filtered")

  - name: dataset__joined
    description: A test to validate the functionality of join clauses in aql.
    data_tests:
      - dbt_utils.equality:
          compare_model: ref("output__joined")

