
# Project Name
name: dbt_activity_schema_integration_tests
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'

config-version: 2

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  +materialized: "{{ env_var('DBT_MATERIALIZATION', 'table') }}"
  +format: csv

vars:
  dbt_activity_schema:
    column_configuration:
      included_optional_columns:
        - revenue_impact
        - link
      column_aliases:
        feature_json: attributes
    streams:
      customer_stream:
        skip_stream: false
        customer_id_alias: entity_uuid
        anonymous_customer_id_alias: anonymous_entity_uuid
        model_prefix: customer__


flags:
  send_anonymous_usage_stats: False
  use_colors: True


seeds:
  dbt_activity_schema_integration_tests:
    datasets:
      +column_types:
        customer_id: "{{ 'string' if target.name == 'bigquery' else 'text' }}"

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_activity_schema_integration_tests', 'dbt_activity_schema', 'dbt']
