config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  outputs:
    duckdb:
      type: duckdb
      path: ":memory:"
      database: memory
      external_root: tmp/materialized # Materialize Models as CSV for Inspection

    postgres:
      type: postgres
      threads: 2
      host: localhost
      port: 5432
      user: ""
      pass: ""
      dbname: dbt_activity_schema_integration_tests
      schema: main

    bigquery:
      type: bigquery
      method: service-account
      project: dbt-activity-schema
      dataset: dbt_activity_schema_integration_tests
      threads: 4 # Must be a value of 1 or greater
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"
      OPTIONAL_CONFIG: VALUE

    snowflake:
      type: snowflake
      account: test
      host: snowflake.localhost.localstack.cloud

      # User/password auth
      user: test
      password: test

      role: test
      database: test
      warehouse: test
      schema: test
      threads: 1
      client_session_keep_alive: False

  target: duckdb
