version: 2

models:

  - name: dataset__time_spine
    description: A test to validate the functionality of macro-based dataset generation.
    tests:
      - dbt_utils.equality:
          compare_model: ref("output__time_spine")
