version: 2

models:

  - name: dataset__filtered__query_stream_macro
    description: A test to validate the functionality of macro-based dataset generation.
    data_tests:
      - dbt_utils.equality:
          compare_model: ref("output__filtered__query_stream_macro")

  - name: dataset__joined__query_stream_macro
    description: A test to validate the functionality of macro-based dataset generation.
    data_tests:
      - dbt_utils.equality:
          compare_model: ref("output__joined__query_stream_macro")

